language: go
sudo: false
go:
- 1.8.x
- 1.9.x
cache:
  directories:
  - $HOME/local
before_install:
- go get github.com/golang/dep/cmd/dep
install:
- dep ensure
script:
- make test-all
env:
  global:
  - "PATH=$PATH:$HOME/local/bin"
notifications:
  email:
    on_success: never